//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int SalesId { get; set; }
        public System.DateTime SalesDate { get; set; }
        public int ProductMappingId { get; set; }
        public decimal Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    
        public virtual ProductSiteMapping ProductSiteMapping { get; set; }
    }
}
