//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderDetail
    {
        public int ProductOrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductMappingId { get; set; }
        public int OrderStatus { get; set; }
        public string OrderAddress { get; set; }
        public System.DateTime DeliveryExpectedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string DeliveredBy { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverNumber { get; set; }
        public string JCBDriverNumber { get; set; }
        public string RoyaltyNumber { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    
        public virtual ProductOrder ProductOrder { get; set; }
        public virtual ProductSiteMapping ProductSiteMapping { get; set; }
    }
}
